<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('centers')->insert([
            'id' => 1,
            'name' => '-- Chọn trung tâm --',
            'short_description' => '-- Chọn trung tâm --',
            'phone' => '01234567899',
            'email' => 'admin@knowledge.vn',
            'slug' => 'knowledge-vn',
            'meta_title' => 'KNOWLEDGE.VN',
        ]);

        DB::unprepared("UPDATE centers SET id=0");

        $grades = [
            ['id' => 1, 'name' => 'Lớp 1'],
            ['id' => 2, 'name' => 'Lớp 2'],
            ['id' => 3, 'name' => 'Lớp 3'],
            ['id' => 4, 'name' => 'Lớp 4'],
            ['id' => 5, 'name' => 'Lớp 5'],
            ['id' => 6, 'name' => 'Lớp 6'],
            ['id' => 7, 'name' => 'Lớp 7'],
            ['id' => 8, 'name' => 'Lớp 8'],
            ['id' => 9, 'name' => 'Lớp 9'],
            ['id' => 10, 'name' => 'Lớp 10'],
            ['id' => 11, 'name' => 'Lớp 11'],
            ['id' => 12, 'name' => 'Lớp 12'],
            ['id' => 13, 'name' => 'Khác'],
        ];

        DB::table('grades')->insert($grades);

        DB::table('teachers')->insert([
            'id' => 1,
            'name' => '-- Chọn gia sư --',
            'description' => '-- Chọn gia sư --',
            'phone' => '01234567899',
            'email' => 'admin@knowledge.vn',
            'slug' => 'knowledge-vn',
            'meta_title' => 'KNOWLEDGE.VN',
        ]);

        DB::unprepared("UPDATE teachers SET id=0");

        $cities = [
            ['code' => '01', 'name' => 'Thành phố Hà Nội', 'type' => 'Thành phố Trung ương'],
            ['code' => '02', 'name' => 'Tỉnh Hà Giang', 'type' => 'Tỉnh'],
            ['code' => '04', 'name' => 'Tỉnh Cao Bằng', 'type' => 'Tỉnh'],
            ['code' => '06', 'name' => 'Tỉnh Bắc Kạn', 'type' => 'Tỉnh'],
            ['code' => '08', 'name' => 'Tỉnh Tuyên Quang', 'type' => 'Tỉnh'],
            ['code' => '10', 'name' => 'Tỉnh Lào Cai', 'type' => 'Tỉnh'],
            ['code' => '11', 'name' => 'Tỉnh Điện Biên', 'type' => 'Tỉnh'],
            ['code' => '12', 'name' => 'Tỉnh Lai Châu', 'type' => 'Tỉnh'],
            ['code' => '14', 'name' => 'Tỉnh Sơn La', 'type' => 'Tỉnh'],
            ['code' => '15', 'name' => 'Tỉnh Yên Bái', 'type' => 'Tỉnh'],
            ['code' => '17', 'name' => 'Tỉnh Hoà Bình', 'type' => 'Tỉnh'],
            ['code' => '19', 'name' => 'Tỉnh Thái Nguyên', 'type' => 'Tỉnh'],
            ['code' => '20', 'name' => 'Tỉnh Lạng Sơn', 'type' => 'Tỉnh'],
            ['code' => '22', 'name' => 'Tỉnh Quảng Ninh', 'type' => 'Tỉnh'],
            ['code' => '24', 'name' => 'Tỉnh Bắc Giang', 'type' => 'Tỉnh'],
            ['code' => '25', 'name' => 'Tỉnh Phú Thọ', 'type' => 'Tỉnh'],
            ['code' => '26', 'name' => 'Tỉnh Vĩnh Phúc', 'type' => 'Tỉnh'],
            ['code' => '27', 'name' => 'Tỉnh Bắc Ninh', 'type' => 'Tỉnh'],
            ['code' => '30', 'name' => 'Tỉnh Hải Dương', 'type' => 'Tỉnh'],
            ['code' => '31', 'name' => 'Thành phố Hải Phòng', 'type' => 'Thành phố Trung ương'],
            ['code' => '33', 'name' => 'Tỉnh Hưng Yên', 'type' => 'Tỉnh'],
            ['code' => '34', 'name' => 'Tỉnh Thái Bình', 'type' => 'Tỉnh'],
            ['code' => '35', 'name' => 'Tỉnh Hà Nam', 'type' => 'Tỉnh'],
            ['code' => '36', 'name' => 'Tỉnh Nam Định', 'type' => 'Tỉnh'],
            ['code' => '37', 'name' => 'Tỉnh Ninh Bình', 'type' => 'Tỉnh'],
            ['code' => '38', 'name' => 'Tỉnh Thanh Hóa', 'type' => 'Tỉnh'],
            ['code' => '40', 'name' => 'Tỉnh Nghệ An', 'type' => 'Tỉnh'],
            ['code' => '42', 'name' => 'Tỉnh Hà Tĩnh', 'type' => 'Tỉnh'],
            ['code' => '44', 'name' => 'Tỉnh Quảng Bình', 'type' => 'Tỉnh'],
            ['code' => '45', 'name' => 'Tỉnh Quảng Trị', 'type' => 'Tỉnh'],
            ['code' => '46', 'name' => 'Tỉnh Thừa Thiên Huế', 'type' => 'Tỉnh'],
            ['code' => '48', 'name' => 'Thành phố Đà Nẵng', 'type' => 'Thành phố Trung ương'],
            ['code' => '49', 'name' => 'Tỉnh Quảng Nam', 'type' => 'Tỉnh'],
            ['code' => '51', 'name' => 'Tỉnh Quảng Ngãi', 'type' => 'Tỉnh'],
            ['code' => '52', 'name' => 'Tỉnh Bình Định', 'type' => 'Tỉnh'],
            ['code' => '54', 'name' => 'Tỉnh Phú Yên', 'type' => 'Tỉnh'],
            ['code' => '56', 'name' => 'Tỉnh Khánh Hòa', 'type' => 'Tỉnh'],
            ['code' => '58', 'name' => 'Tỉnh Ninh Thuận', 'type' => 'Tỉnh'],
            ['code' => '60', 'name' => 'Tỉnh Bình Thuận', 'type' => 'Tỉnh'],
            ['code' => '62', 'name' => 'Tỉnh Kon Tum', 'type' => 'Tỉnh'],
            ['code' => '64', 'name' => 'Tỉnh Gia Lai', 'type' => 'Tỉnh'],
            ['code' => '66', 'name' => 'Tỉnh Đắk Lắk', 'type' => 'Tỉnh'],
            ['code' => '67', 'name' => 'Tỉnh Đắk Nông', 'type' => 'Tỉnh'],
            ['code' => '68', 'name' => 'Tỉnh Lâm Đồng', 'type' => 'Tỉnh'],
            ['code' => '70', 'name' => 'Tỉnh Bình Phước', 'type' => 'Tỉnh'],
            ['code' => '72', 'name' => 'Tỉnh Tây Ninh', 'type' => 'Tỉnh'],
            ['code' => '74', 'name' => 'Tỉnh Bình Dương', 'type' => 'Tỉnh'],
            ['code' => '75', 'name' => 'Tỉnh Đồng Nai', 'type' => 'Tỉnh'],
            ['code' => '77', 'name' => 'Tỉnh Bà Rịa - Vũng Tàu', 'type' => 'Tỉnh'],
            ['code' => '79', 'name' => 'Thành phố Hồ Chí Minh', 'type' => 'Thành phố Trung ương'],
            ['code' => '80', 'name' => 'Tỉnh Long An', 'type' => 'Tỉnh'],
            ['code' => '82', 'name' => 'Tỉnh Tiền Giang', 'type' => 'Tỉnh'],
            ['code' => '83', 'name' => 'Tỉnh Bến Tre', 'type' => 'Tỉnh'],
            ['code' => '84', 'name' => 'Tỉnh Trà Vinh', 'type' => 'Tỉnh'],
            ['code' => '86', 'name' => 'Tỉnh Vĩnh Long', 'type' => 'Tỉnh'],
            ['code' => '87', 'name' => 'Tỉnh Đồng Tháp', 'type' => 'Tỉnh'],
            ['code' => '89', 'name' => 'Tỉnh An Giang', 'type' => 'Tỉnh'],
            ['code' => '91', 'name' => 'Tỉnh Kiên Giang', 'type' => 'Tỉnh'],
            ['code' => '92', 'name' => 'Thành phố Cần Thơ', 'type' => 'Thành phố Trung ương'],
            ['code' => '93', 'name' => 'Tỉnh Hậu Giang', 'type' => 'Tỉnh'],
            ['code' => '94', 'name' => 'Tỉnh Sóc Trăng', 'type' => 'Tỉnh'],
            ['code' => '95', 'name' => 'Tỉnh Bạc Liêu', 'type' => 'Tỉnh'],
            ['code' => '96', 'name' => 'Tỉnh Cà Mau', 'type' => 'Tỉnh']
        ];

        DB::table('cities')->insert($cities);


        $districts = [
            ['code' => '001', 'name' => 'Quận Ba Đình', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '002', 'name' => 'Quận Hoàn Kiếm', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '003', 'name' => 'Quận Tây Hồ', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '004', 'name' => 'Quận Long Biên', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '005', 'name' => 'Quận Cầu Giấy', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '006', 'name' => 'Quận Đống Đa', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '007', 'name' => 'Quận Hai Bà Trưng', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '008', 'name' => 'Quận Hoàng Mai', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '009', 'name' => 'Quận Thanh Xuân', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '016', 'name' => 'Huyện Sóc Sơn', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '017', 'name' => 'Huyện Đông Anh', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '018', 'name' => 'Huyện Gia Lâm', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '019', 'name' => 'Quận Nam Từ Liêm', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '020', 'name' => 'Huyện Thanh Trì', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '021', 'name' => 'Quận Bắc Từ Liêm', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '024', 'name' => 'Thành phố Hà Giang', 'type' => 'Thành phố', 'code_city' => '02'],
            ['code' => '026', 'name' => 'Huyện Đồng Văn', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '027', 'name' => 'Huyện Mèo Vạc', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '028', 'name' => 'Huyện Yên Minh', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '029', 'name' => 'Huyện Quản Bạ', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '030', 'name' => 'Huyện Vị Xuyên', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '031', 'name' => 'Huyện Bắc Mê', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '032', 'name' => 'Huyện Hoàng Su Phì', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '033', 'name' => 'Huyện Xín Mần', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '034', 'name' => 'Huyện Bắc Quang', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '035', 'name' => 'Huyện Quang Bình', 'type' => 'Huyện', 'code_city' => '02'],
            ['code' => '040', 'name' => 'Thành phố Cao Bằng', 'type' => 'Thành phố', 'code_city' => '04'],
            ['code' => '042', 'name' => 'Huyện Bảo Lâm', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '043', 'name' => 'Huyện Bảo Lạc', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '044', 'name' => 'Huyện Thông Nông', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '045', 'name' => 'Huyện Hà Quảng', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '046', 'name' => 'Huyện Trà Lĩnh', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '047', 'name' => 'Huyện Trùng Khánh', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '048', 'name' => 'Huyện Hạ Lang', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '049', 'name' => 'Huyện Quảng Uyên', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '050', 'name' => 'Huyện Phục Hoà', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '051', 'name' => 'Huyện Hoà An', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '052', 'name' => 'Huyện Nguyên Bình', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '053', 'name' => 'Huyện Thạch An', 'type' => 'Huyện', 'code_city' => '04'],
            ['code' => '058', 'name' => 'Thành phố Bắc Kạn', 'type' => 'Thành phố', 'code_city' => '06'],
            ['code' => '060', 'name' => 'Huyện Pác Nặm', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '061', 'name' => 'Huyện Ba Bể', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '062', 'name' => 'Huyện Ngân Sơn', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '063', 'name' => 'Huyện Bạch Thông', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '064', 'name' => 'Huyện Chợ Đồn', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '065', 'name' => 'Huyện Chợ Mới', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '066', 'name' => 'Huyện Na Rì', 'type' => 'Huyện', 'code_city' => '06'],
            ['code' => '070', 'name' => 'Thành phố Tuyên Quang', 'type' => 'Thành phố', 'code_city' => '08'],
            ['code' => '071', 'name' => 'Huyện Lâm Bình', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '072', 'name' => 'Huyện Nà Hang', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '073', 'name' => 'Huyện Chiêm Hóa', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '074', 'name' => 'Huyện Hàm Yên', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '075', 'name' => 'Huyện Yên Sơn', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '076', 'name' => 'Huyện Sơn Dương', 'type' => 'Huyện', 'code_city' => '08'],
            ['code' => '080', 'name' => 'Thành phố Lào Cai', 'type' => 'Thành phố', 'code_city' => '10'],
            ['code' => '082', 'name' => 'Huyện Bát Xát', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '083', 'name' => 'Huyện Mường Khương', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '084', 'name' => 'Huyện Si Ma Cai', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '085', 'name' => 'Huyện Bắc Hà', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '086', 'name' => 'Huyện Bảo Thắng', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '087', 'name' => 'Huyện Bảo Yên', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '088', 'name' => 'Huyện Sa Pa', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '089', 'name' => 'Huyện Văn Bàn', 'type' => 'Huyện', 'code_city' => '10'],
            ['code' => '094', 'name' => 'Thành phố Điện Biên Phủ', 'type' => 'Thành phố', 'code_city' => '11'],
            ['code' => '095', 'name' => 'Thị xã  Mường Lay', 'type' => 'Thị xã', 'code_city' => '11'],
            ['code' => '096', 'name' => 'Huyện Mường Nhé', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '097', 'name' => 'Huyện Mường Chà', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '098', 'name' => 'Huyện Tủa Chùa', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '099', 'name' => 'Huyện Tuần Giáo', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '100', 'name' => 'Huyện Điện Biên', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '101', 'name' => 'Huyện Điện Biên Đông', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '102', 'name' => 'Huyện Mường Ảng', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '103', 'name' => 'Huyện Nậm Pồ', 'type' => 'Huyện', 'code_city' => '11'],
            ['code' => '105', 'name' => 'Thành phố Lai Châu', 'type' => 'Thành phố', 'code_city' => '12'],
            ['code' => '106', 'name' => 'Huyện Tam Đường', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '107', 'name' => 'Huyện Mường Tè', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '108', 'name' => 'Huyện Sìn Hồ', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '109', 'name' => 'Huyện Phong Thổ', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '110', 'name' => 'Huyện Than Uyên', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '111', 'name' => 'Huyện Tân Uyên', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '112', 'name' => 'Huyện Nậm Nhùn', 'type' => 'Huyện', 'code_city' => '12'],
            ['code' => '116', 'name' => 'Thành phố Sơn La', 'type' => 'Thành phố', 'code_city' => '14'],
            ['code' => '118', 'name' => 'Huyện Quỳnh Nhai', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '119', 'name' => 'Huyện Thuận Châu', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '120', 'name' => 'Huyện Mường La', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '121', 'name' => 'Huyện Bắc Yên', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '122', 'name' => 'Huyện Phù Yên', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '123', 'name' => 'Huyện Mộc Châu', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '124', 'name' => 'Huyện Yên Châu', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '125', 'name' => 'Huyện Mai Sơn', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '126', 'name' => 'Huyện Sông Mã', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '127', 'name' => 'Huyện Sốp Cộp', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '128', 'name' => 'Huyện Vân Hồ', 'type' => 'Huyện', 'code_city' => '14'],
            ['code' => '132', 'name' => 'Thành phố Yên Bái', 'type' => 'Thành phố', 'code_city' => '15'],
            ['code' => '133', 'name' => 'Thị xã  Nghĩa Lộ', 'type' => 'Thị xã', 'code_city' => '15'],
            ['code' => '135', 'name' => 'Huyện Lục Yên', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '136', 'name' => 'Huyện Văn Yên', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '137', 'name' => 'Huyện Mù Căng Chải', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '138', 'name' => 'Huyện Trấn Yên', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '139', 'name' => 'Huyện Trạm Tấu', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '140', 'name' => 'Huyện Văn Chấn', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '141', 'name' => 'Huyện Yên Bình', 'type' => 'Huyện', 'code_city' => '15'],
            ['code' => '148', 'name' => 'Thành phố Hòa Bình', 'type' => 'Thành phố', 'code_city' => '17'],
            ['code' => '150', 'name' => 'Huyện Đà Bắc', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '151', 'name' => 'Huyện Kỳ Sơn', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '152', 'name' => 'Huyện Lương Sơn', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '153', 'name' => 'Huyện Kim Bôi', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '154', 'name' => 'Huyện Cao Phong', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '155', 'name' => 'Huyện Tân Lạc', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '156', 'name' => 'Huyện Mai Châu', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '157', 'name' => 'Huyện Lạc Sơn', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '158', 'name' => 'Huyện Yên Thủy', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '159', 'name' => 'Huyện Lạc Thủy', 'type' => 'Huyện', 'code_city' => '17'],
            ['code' => '164', 'name' => 'Thành phố Thái Nguyên', 'type' => 'Thành phố', 'code_city' => '19'],
            ['code' => '165', 'name' => 'Thành phố Sông Công', 'type' => 'Thành phố', 'code_city' => '19'],
            ['code' => '167', 'name' => 'Huyện Định Hóa', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '168', 'name' => 'Huyện Phú Lương', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '169', 'name' => 'Huyện Đồng Hỷ', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '170', 'name' => 'Huyện Võ Nhai', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '171', 'name' => 'Huyện Đại Từ', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '172', 'name' => 'Thị xã  Phổ Yên', 'type' => 'Thị xã', 'code_city' => '19'],
            ['code' => '173', 'name' => 'Huyện Phú Bình', 'type' => 'Huyện', 'code_city' => '19'],
            ['code' => '178', 'name' => 'Thành phố Lạng Sơn', 'type' => 'Thành phố', 'code_city' => '20'],
            ['code' => '180', 'name' => 'Huyện Tràng Định', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '181', 'name' => 'Huyện Bình Gia', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '182', 'name' => 'Huyện Văn Lãng', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '183', 'name' => 'Huyện Cao Lộc', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '184', 'name' => 'Huyện Văn Quan', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '185', 'name' => 'Huyện Bắc Sơn', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '186', 'name' => 'Huyện Hữu Lũng', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '187', 'name' => 'Huyện Chi Lăng', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '188', 'name' => 'Huyện Lộc Bình', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '189', 'name' => 'Huyện Đình Lập', 'type' => 'Huyện', 'code_city' => '20'],
            ['code' => '193', 'name' => 'Thành phố Hạ Long', 'type' => 'Thành phố', 'code_city' => '22'],
            ['code' => '194', 'name' => 'Thành phố Móng Cái', 'type' => 'Thành phố', 'code_city' => '22'],
            ['code' => '195', 'name' => 'Thành phố Cẩm Phả', 'type' => 'Thành phố', 'code_city' => '22'],
            ['code' => '196', 'name' => 'Thành phố Uông Bí', 'type' => 'Thành phố', 'code_city' => '22'],
            ['code' => '198', 'name' => 'Huyện Bình Liêu', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '199', 'name' => 'Huyện Tiên Yên', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '200', 'name' => 'Huyện Đầm Hà', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '201', 'name' => 'Huyện Hải Hà', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '202', 'name' => 'Huyện Ba Chẽ', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '203', 'name' => 'Huyện Vân Đồn', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '204', 'name' => 'Huyện Hoành Bồ', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '205', 'name' => 'Thị xã  Đông Triều', 'type' => 'Thị xã', 'code_city' => '22'],
            ['code' => '206', 'name' => 'Thị xã  Quảng Yên', 'type' => 'Thị xã', 'code_city' => '22'],
            ['code' => '207', 'name' => 'Huyện Cô Tô', 'type' => 'Huyện', 'code_city' => '22'],
            ['code' => '213', 'name' => 'Thành phố Bắc Giang', 'type' => 'Thành phố', 'code_city' => '24'],
            ['code' => '215', 'name' => 'Huyện Yên Thế', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '216', 'name' => 'Huyện Tân Yên', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '217', 'name' => 'Huyện Lạng Giang', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '218', 'name' => 'Huyện Lục Nam', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '219', 'name' => 'Huyện Lục Ngạn', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '220', 'name' => 'Huyện Sơn Động', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '221', 'name' => 'Huyện Yên Dũng', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '222', 'name' => 'Huyện Việt Yên', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '223', 'name' => 'Huyện Hiệp Hòa', 'type' => 'Huyện', 'code_city' => '24'],
            ['code' => '227', 'name' => 'Thành phố Việt Trì', 'type' => 'Thành phố', 'code_city' => '25'],
            ['code' => '228', 'name' => 'Thị xã  Phú Thọ', 'type' => 'Thị xã', 'code_city' => '25'],
            ['code' => '230', 'name' => 'Huyện Đoan Hùng', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '231', 'name' => 'Huyện Hạ Hoà', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '232', 'name' => 'Huyện Thanh Ba', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '233', 'name' => 'Huyện Phù Ninh', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '234', 'name' => 'Huyện Yên Lập', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '235', 'name' => 'Huyện Cẩm Khê', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '236', 'name' => 'Huyện Tam Nông', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '237', 'name' => 'Huyện Lâm Thao', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '238', 'name' => 'Huyện Thanh Sơn', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '239', 'name' => 'Huyện Thanh Thuỷ', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '240', 'name' => 'Huyện Tân Sơn', 'type' => 'Huyện', 'code_city' => '25'],
            ['code' => '243', 'name' => 'Thành phố Vĩnh Yên', 'type' => 'Thành phố', 'code_city' => '26'],
            ['code' => '244', 'name' => 'Thị xã  Phúc Yên', 'type' => 'Thị xã', 'code_city' => '26'],
            ['code' => '246', 'name' => 'Huyện Lập Thạch', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '247', 'name' => 'Huyện Tam Dương', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '248', 'name' => 'Huyện Tam Đảo', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '249', 'name' => 'Huyện Bình Xuyên', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '250', 'name' => 'Huyện Mê Linh', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '251', 'name' => 'Huyện Yên Lạc', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '252', 'name' => 'Huyện Vĩnh Tường', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '253', 'name' => 'Huyện Sông Lô', 'type' => 'Huyện', 'code_city' => '26'],
            ['code' => '256', 'name' => 'Thành phố Bắc Ninh', 'type' => 'Thành phố', 'code_city' => '27'],
            ['code' => '258', 'name' => 'Huyện Yên Phong', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '259', 'name' => 'Huyện Quế Võ', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '260', 'name' => 'Huyện Tiên Du', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '261', 'name' => 'Thị xã  Từ Sơn', 'type' => 'Thị xã', 'code_city' => '27'],
            ['code' => '262', 'name' => 'Huyện Thuận Thành', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '263', 'name' => 'Huyện Gia Bình', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '264', 'name' => 'Huyện Lương Tài', 'type' => 'Huyện', 'code_city' => '27'],
            ['code' => '268', 'name' => 'Quận Hà Đông', 'type' => 'Quận', 'code_city' => '01'],
            ['code' => '269', 'name' => 'Thị xã  Sơn Tây', 'type' => 'Thị xã', 'code_city' => '01'],
            ['code' => '271', 'name' => 'Huyện Ba Vì', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '272', 'name' => 'Huyện Phúc Thọ', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '273', 'name' => 'Huyện Đan Phượng', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '274', 'name' => 'Huyện Hoài Đức', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '275', 'name' => 'Huyện Quốc Oai', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '276', 'name' => 'Huyện Thạch Thất', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '277', 'name' => 'Huyện Chương Mỹ', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '278', 'name' => 'Huyện Thanh Oai', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '279', 'name' => 'Huyện Thường Tín', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '280', 'name' => 'Huyện Phú Xuyên', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '281', 'name' => 'Huyện Ứng Hòa', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '282', 'name' => 'Huyện Mỹ Đức', 'type' => 'Huyện', 'code_city' => '01'],
            ['code' => '288', 'name' => 'Thành phố Hải Dương', 'type' => 'Thành phố', 'code_city' => '30'],
            ['code' => '290', 'name' => 'Thị xã  Chí Linh', 'type' => 'Thị xã', 'code_city' => '30'],
            ['code' => '291', 'name' => 'Huyện Nam Sách', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '292', 'name' => 'Huyện Kinh Môn', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '293', 'name' => 'Huyện Kim Thành', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '294', 'name' => 'Huyện Thanh Hà', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '295', 'name' => 'Huyện Cẩm Giàng', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '296', 'name' => 'Huyện Bình Giang', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '297', 'name' => 'Huyện Gia Lộc', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '298', 'name' => 'Huyện Tứ Kỳ', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '299', 'name' => 'Huyện Ninh Giang', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '300', 'name' => 'Huyện Thanh Miện', 'type' => 'Huyện', 'code_city' => '30'],
            ['code' => '303', 'name' => 'Quận Hồng Bàng', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '304', 'name' => 'Quận Ngô Quyền', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '305', 'name' => 'Quận Lê Chân', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '306', 'name' => 'Quận Hải An', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '307', 'name' => 'Quận Kiến An', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '308', 'name' => 'Quận Đồ Sơn', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '309', 'name' => 'Quận Dương Kinh', 'type' => 'Quận', 'code_city' => '31'],
            ['code' => '311', 'name' => 'Huyện Thuỷ Nguyên', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '312', 'name' => 'Huyện An Dương', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '313', 'name' => 'Huyện An Lão', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '314', 'name' => 'Huyện Kiến Thuỵ', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '315', 'name' => 'Huyện Tiên Lãng', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '316', 'name' => 'Huyện Vĩnh Bảo', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '317', 'name' => 'Huyện Cát Hải', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '318', 'name' => 'Huyện Bạch Long Vĩ', 'type' => 'Huyện', 'code_city' => '31'],
            ['code' => '323', 'name' => 'Thành phố Hưng Yên', 'type' => 'Thành phố', 'code_city' => '33'],
            ['code' => '325', 'name' => 'Huyện Văn Lâm', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '326', 'name' => 'Huyện Văn Giang', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '327', 'name' => 'Huyện Yên Mỹ', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '328', 'name' => 'Huyện Mỹ Hào', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '329', 'name' => 'Huyện Ân Thi', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '330', 'name' => 'Huyện Khoái Châu', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '331', 'name' => 'Huyện Kim Động', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '332', 'name' => 'Huyện Tiên Lữ', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '333', 'name' => 'Huyện Phù Cừ', 'type' => 'Huyện', 'code_city' => '33'],
            ['code' => '336', 'name' => 'Thành phố Thái Bình', 'type' => 'Thành phố', 'code_city' => '34'],
            ['code' => '338', 'name' => 'Huyện Quỳnh Phụ', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '339', 'name' => 'Huyện Hưng Hà', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '340', 'name' => 'Huyện Đông Hưng', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '341', 'name' => 'Huyện Thái Thụy', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '342', 'name' => 'Huyện Tiền Hải', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '343', 'name' => 'Huyện Kiến Xương', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '344', 'name' => 'Huyện Vũ Thư', 'type' => 'Huyện', 'code_city' => '34'],
            ['code' => '347', 'name' => 'Thành phố Phủ Lý', 'type' => 'Thành phố', 'code_city' => '35'],
            ['code' => '349', 'name' => 'Huyện Duy Tiên', 'type' => 'Huyện', 'code_city' => '35'],
            ['code' => '350', 'name' => 'Huyện Kim Bảng', 'type' => 'Huyện', 'code_city' => '35'],
            ['code' => '351', 'name' => 'Huyện Thanh Liêm', 'type' => 'Huyện', 'code_city' => '35'],
            ['code' => '352', 'name' => 'Huyện Bình Lục', 'type' => 'Huyện', 'code_city' => '35'],
            ['code' => '353', 'name' => 'Huyện Lý Nhân', 'type' => 'Huyện', 'code_city' => '35'],
            ['code' => '356', 'name' => 'Thành phố Nam Định', 'type' => 'Thành phố', 'code_city' => '36'],
            ['code' => '358', 'name' => 'Huyện Mỹ Lộc', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '359', 'name' => 'Huyện Vụ Bản', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '360', 'name' => 'Huyện Ý Yên', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '361', 'name' => 'Huyện Nghĩa Hưng', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '362', 'name' => 'Huyện Nam Trực', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '363', 'name' => 'Huyện Trực Ninh', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '364', 'name' => 'Huyện Xuân Trường', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '365', 'name' => 'Huyện Giao Thủy', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '366', 'name' => 'Huyện Hải Hậu', 'type' => 'Huyện', 'code_city' => '36'],
            ['code' => '369', 'name' => 'Thành phố Ninh Bình', 'type' => 'Thành phố', 'code_city' => '37'],
            ['code' => '370', 'name' => 'Thành phố Tam Điệp', 'type' => 'Thành phố', 'code_city' => '37'],
            ['code' => '372', 'name' => 'Huyện Nho Quan', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '373', 'name' => 'Huyện Gia Viễn', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '374', 'name' => 'Huyện Hoa Lư', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '375', 'name' => 'Huyện Yên Khánh', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '376', 'name' => 'Huyện Kim Sơn', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '377', 'name' => 'Huyện Yên Mô', 'type' => 'Huyện', 'code_city' => '37'],
            ['code' => '380', 'name' => 'Thành phố Thanh Hóa', 'type' => 'Thành phố', 'code_city' => '38'],
            ['code' => '381', 'name' => 'Thị xã  Bỉm Sơn', 'type' => 'Thị xã', 'code_city' => '38'],
            ['code' => '382', 'name' => 'Thị xã  Sầm Sơn', 'type' => 'Thị xã', 'code_city' => '38'],
            ['code' => '384', 'name' => 'Huyện Mường Lát', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '385', 'name' => 'Huyện Quan Hóa', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '386', 'name' => 'Huyện Bá Thước', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '387', 'name' => 'Huyện Quan Sơn', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '388', 'name' => 'Huyện Lang Chánh', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '389', 'name' => 'Huyện Ngọc Lặc', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '390', 'name' => 'Huyện Cẩm Thủy', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '391', 'name' => 'Huyện Thạch Thành', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '392', 'name' => 'Huyện Hà Trung', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '393', 'name' => 'Huyện Vĩnh Lộc', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '394', 'name' => 'Huyện Yên Định', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '395', 'name' => 'Huyện Thọ Xuân', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '396', 'name' => 'Huyện Thường Xuân', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '397', 'name' => 'Huyện Triệu Sơn', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '398', 'name' => 'Huyện Thiệu Hóa', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '399', 'name' => 'Huyện Hoằng Hóa', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '400', 'name' => 'Huyện Hậu Lộc', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '401', 'name' => 'Huyện Nga Sơn', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '402', 'name' => 'Huyện Như Xuân', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '403', 'name' => 'Huyện Như Thanh', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '404', 'name' => 'Huyện Nông Cống', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '405', 'name' => 'Huyện Đông Sơn', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '406', 'name' => 'Huyện Quảng Xương', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '407', 'name' => 'Huyện Tĩnh Gia', 'type' => 'Huyện', 'code_city' => '38'],
            ['code' => '412', 'name' => 'Thành phố Vinh', 'type' => 'Thành phố', 'code_city' => '40'],
            ['code' => '413', 'name' => 'Thị xã  Cửa Lò', 'type' => 'Thị xã', 'code_city' => '40'],
            ['code' => '414', 'name' => 'Thị xã  Thái Hoà', 'type' => 'Thị xã', 'code_city' => '40'],
            ['code' => '415', 'name' => 'Huyện Quế Phong', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '416', 'name' => 'Huyện Quỳ Châu', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '417', 'name' => 'Huyện Kỳ Sơn', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '418', 'name' => 'Huyện Tương Dương', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '419', 'name' => 'Huyện Nghĩa Đàn', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '420', 'name' => 'Huyện Quỳ Hợp', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '421', 'name' => 'Huyện Quỳnh Lưu', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '422', 'name' => 'Huyện Con Cuông', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '423', 'name' => 'Huyện Tân Kỳ', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '424', 'name' => 'Huyện Anh Sơn', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '425', 'name' => 'Huyện Diễn Châu', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '426', 'name' => 'Huyện Yên Thành', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '427', 'name' => 'Huyện Đô Lương', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '428', 'name' => 'Huyện Thanh Chương', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '429', 'name' => 'Huyện Nghi Lộc', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '430', 'name' => 'Huyện Nam Đàn', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '431', 'name' => 'Huyện Hưng Nguyên', 'type' => 'Huyện', 'code_city' => '40'],
            ['code' => '432', 'name' => 'Thị xã  Hoàng Mai', 'type' => 'Thị xã', 'code_city' => '40'],
            ['code' => '436', 'name' => 'Thành phố Hà Tĩnh', 'type' => 'Thành phố', 'code_city' => '42'],
            ['code' => '437', 'name' => 'Thị xã  Hồng Lĩnh', 'type' => 'Thị xã', 'code_city' => '42'],
            ['code' => '439', 'name' => 'Huyện Hương Sơn', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '440', 'name' => 'Huyện Đức Thọ', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '441', 'name' => 'Huyện Vũ Quang', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '442', 'name' => 'Huyện Nghi Xuân', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '443', 'name' => 'Huyện Can Lộc', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '444', 'name' => 'Huyện Hương Khê', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '445', 'name' => 'Huyện Thạch Hà', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '446', 'name' => 'Huyện Cẩm Xuyên', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '447', 'name' => 'Huyện Kỳ Anh', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '448', 'name' => 'Huyện Lộc Hà', 'type' => 'Huyện', 'code_city' => '42'],
            ['code' => '449', 'name' => 'Thị xã  Kỳ Anh', 'type' => 'Thị xã', 'code_city' => '42'],
            ['code' => '450', 'name' => 'Thành phố Đồng Hới', 'type' => 'Thành phố', 'code_city' => '44'],
            ['code' => '452', 'name' => 'Huyện Minh Hóa', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '453', 'name' => 'Huyện Tuyên Hóa', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '454', 'name' => 'Huyện Quảng Trạch', 'type' => 'Thị xã', 'code_city' => '44'],
            ['code' => '455', 'name' => 'Huyện Bố Trạch', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '456', 'name' => 'Huyện Quảng Ninh', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '457', 'name' => 'Huyện Lệ Thủy', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '458', 'name' => 'Thị xã  Ba Đồn', 'type' => 'Huyện', 'code_city' => '44'],
            ['code' => '461', 'name' => 'Thành phố Đông Hà', 'type' => 'Thành phố', 'code_city' => '45'],
            ['code' => '462', 'name' => 'Thị xã  Quảng Trị', 'type' => 'Thị xã', 'code_city' => '45'],
            ['code' => '464', 'name' => 'Huyện Vĩnh Linh', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '465', 'name' => 'Huyện Hướng Hóa', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '466', 'name' => 'Huyện Gio Linh', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '467', 'name' => 'Huyện Đa Krông', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '468', 'name' => 'Huyện Cam Lộ', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '469', 'name' => 'Huyện Triệu Phong', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '470', 'name' => 'Huyện Hải Lăng', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '471', 'name' => 'Huyện Cồn Cỏ', 'type' => 'Huyện', 'code_city' => '45'],
            ['code' => '474', 'name' => 'Thành phố Huế', 'type' => 'Thành phố', 'code_city' => '46'],
            ['code' => '476', 'name' => 'Huyện Phong Điền', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '477', 'name' => 'Huyện Quảng Điền', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '478', 'name' => 'Huyện Phú Vang', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '479', 'name' => 'Thị xã  Hương Thủy', 'type' => 'Thị xã', 'code_city' => '46'],
            ['code' => '480', 'name' => 'Thị xã  Hương Trà', 'type' => 'Thị xã', 'code_city' => '46'],
            ['code' => '481', 'name' => 'Huyện A Lưới', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '482', 'name' => 'Huyện Phú Lộc', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '483', 'name' => 'Huyện Nam Đông', 'type' => 'Huyện', 'code_city' => '46'],
            ['code' => '490', 'name' => 'Quận Liên Chiểu', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '491', 'name' => 'Quận Thanh Khê', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '492', 'name' => 'Quận Hải Châu', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '493', 'name' => 'Quận Sơn Trà', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '494', 'name' => 'Quận Ngũ Hành Sơn', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '495', 'name' => 'Quận Cẩm Lệ', 'type' => 'Quận', 'code_city' => '48'],
            ['code' => '497', 'name' => 'Huyện Hòa Vang', 'type' => 'Huyện', 'code_city' => '48'],
            ['code' => '498', 'name' => 'Huyện Hoàng Sa', 'type' => 'Huyện', 'code_city' => '48'],
            ['code' => '502', 'name' => 'Thành phố Tam Kỳ', 'type' => 'Thành phố', 'code_city' => '49'],
            ['code' => '503', 'name' => 'Thành phố Hội An', 'type' => 'Thành phố', 'code_city' => '49'],
            ['code' => '504', 'name' => 'Huyện Tây Giang', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '505', 'name' => 'Huyện Đông Giang', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '506', 'name' => 'Huyện Đại Lộc', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '507', 'name' => 'Thị xã  Điện Bàn', 'type' => 'Thị xã', 'code_city' => '49'],
            ['code' => '508', 'name' => 'Huyện Duy Xuyên', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '509', 'name' => 'Huyện Quế Sơn', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '510', 'name' => 'Huyện Nam Giang', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '511', 'name' => 'Huyện Phước Sơn', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '512', 'name' => 'Huyện Hiệp Đức', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '513', 'name' => 'Huyện Thăng Bình', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '514', 'name' => 'Huyện Tiên Phước', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '515', 'name' => 'Huyện Bắc Trà My', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '516', 'name' => 'Huyện Nam Trà My', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '517', 'name' => 'Huyện Núi Thành', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '518', 'name' => 'Huyện Phú Ninh', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '519', 'name' => 'Huyện Nông Sơn', 'type' => 'Huyện', 'code_city' => '49'],
            ['code' => '522', 'name' => 'Thành phố Quảng Ngãi', 'type' => 'Thành phố', 'code_city' => '51'],
            ['code' => '524', 'name' => 'Huyện Bình Sơn', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '525', 'name' => 'Huyện Trà Bồng', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '526', 'name' => 'Huyện Tây Trà', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '527', 'name' => 'Huyện Sơn Tịnh', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '528', 'name' => 'Huyện Tư Nghĩa', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '529', 'name' => 'Huyện Sơn Hà', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '530', 'name' => 'Huyện Sơn Tây', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '531', 'name' => 'Huyện Minh Long', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '532', 'name' => 'Huyện Nghĩa Hành', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '533', 'name' => 'Huyện Mộ Đức', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '534', 'name' => 'Huyện Đức Phổ', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '535', 'name' => 'Huyện Ba Tơ', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '536', 'name' => 'Huyện Lý Sơn', 'type' => 'Huyện', 'code_city' => '51'],
            ['code' => '540', 'name' => 'Thành phố Qui Nhơn', 'type' => 'Thành phố', 'code_city' => '52'],
            ['code' => '542', 'name' => 'Huyện An Lão', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '543', 'name' => 'Huyện Hoài Nhơn', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '544', 'name' => 'Huyện Hoài Ân', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '545', 'name' => 'Huyện Phù Mỹ', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '546', 'name' => 'Huyện Vĩnh Thạnh', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '547', 'name' => 'Huyện Tây Sơn', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '548', 'name' => 'Huyện Phù Cát', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '549', 'name' => 'Thị xã  An Nhơn', 'type' => 'Thị xã', 'code_city' => '52'],
            ['code' => '550', 'name' => 'Huyện Tuy Phước', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '551', 'name' => 'Huyện Vân Canh', 'type' => 'Huyện', 'code_city' => '52'],
            ['code' => '555', 'name' => 'Thành phố Tuy Hoà', 'type' => 'Thành phố', 'code_city' => '54'],
            ['code' => '557', 'name' => 'Thị xã  Sông Cầu', 'type' => 'Thị xã', 'code_city' => '54'],
            ['code' => '558', 'name' => 'Huyện Đồng Xuân', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '559', 'name' => 'Huyện Tuy An', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '560', 'name' => 'Huyện Sơn Hòa', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '561', 'name' => 'Huyện Sông Hinh', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '562', 'name' => 'Huyện Tây Hoà', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '563', 'name' => 'Huyện Phú Hoà', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '564', 'name' => 'Huyện Đông Hòa', 'type' => 'Huyện', 'code_city' => '54'],
            ['code' => '568', 'name' => 'Thành phố Nha Trang', 'type' => 'Thành phố', 'code_city' => '56'],
            ['code' => '569', 'name' => 'Thành phố Cam Ranh', 'type' => 'Thành phố', 'code_city' => '56'],
            ['code' => '570', 'name' => 'Huyện Cam Lâm', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '571', 'name' => 'Huyện Vạn Ninh', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '572', 'name' => 'Thị xã  Ninh Hòa', 'type' => 'Thị xã', 'code_city' => '56'],
            ['code' => '573', 'name' => 'Huyện Khánh Vĩnh', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '574', 'name' => 'Huyện Diên Khánh', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '575', 'name' => 'Huyện Khánh Sơn', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '576', 'name' => 'Huyện Trường Sa', 'type' => 'Huyện', 'code_city' => '56'],
            ['code' => '582', 'name' => 'Thành phố Phan Rang-Tháp Chàm', 'type' => 'Thành phố', 'code_city' => '58'],
            ['code' => '584', 'name' => 'Huyện Bác Ái', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '585', 'name' => 'Huyện Ninh Sơn', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '586', 'name' => 'Huyện Ninh Hải', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '587', 'name' => 'Huyện Ninh Phước', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '588', 'name' => 'Huyện Thuận Bắc', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '589', 'name' => 'Huyện Thuận Nam', 'type' => 'Huyện', 'code_city' => '58'],
            ['code' => '593', 'name' => 'Thành phố Phan Thiết', 'type' => 'Thành phố', 'code_city' => '60'],
            ['code' => '594', 'name' => 'Thị xã  La Gi', 'type' => 'Thị xã', 'code_city' => '60'],
            ['code' => '595', 'name' => 'Huyện Tuy Phong', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '596', 'name' => 'Huyện Bắc Bình', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '597', 'name' => 'Huyện Hàm Thuận Bắc', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '598', 'name' => 'Huyện Hàm Thuận Nam', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '599', 'name' => 'Huyện Tánh Linh', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '600', 'name' => 'Huyện Đức Linh', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '601', 'name' => 'Huyện Hàm Tân', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '602', 'name' => 'Huyện Phú Quí', 'type' => 'Huyện', 'code_city' => '60'],
            ['code' => '608', 'name' => 'Thành phố Kon Tum', 'type' => 'Thành phố', 'code_city' => '62'],
            ['code' => '610', 'name' => 'Huyện Đắk Glei', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '611', 'name' => 'Huyện Ngọc Hồi', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '612', 'name' => 'Huyện Đắk Tô', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '613', 'name' => 'Huyện Kon Plông', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '614', 'name' => 'Huyện Kon Rẫy', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '615', 'name' => 'Huyện Đắk Hà', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '616', 'name' => 'Huyện Sa Thầy', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '617', 'name' => 'Huyện Tu Mơ Rông', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '618', 'name' => 'Huyện Ia H\' Drai', 'type' => 'Huyện', 'code_city' => '62'],
            ['code' => '622', 'name' => 'Thành phố Pleiku', 'type' => 'Thành phố', 'code_city' => '64'],
            ['code' => '623', 'name' => 'Thị xã  An Khê', 'type' => 'Thị xã', 'code_city' => '64'],
            ['code' => '624', 'name' => 'Thị xã  Ayun Pa', 'type' => 'Thị xã', 'code_city' => '64'],
            ['code' => '625', 'name' => 'Huyện KBang', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '626', 'name' => 'Huyện Đăk Đoa', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '627', 'name' => 'Huyện Chư Păh', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '628', 'name' => 'Huyện Ia Grai', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '629', 'name' => 'Huyện Mang Yang', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '630', 'name' => 'Huyện Kông Chro', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '631', 'name' => 'Huyện Đức Cơ', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '632', 'name' => 'Huyện Chư Prông', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '633', 'name' => 'Huyện Chư Sê', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '634', 'name' => 'Huyện Đăk Pơ', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '635', 'name' => 'Huyện Ia Pa', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '637', 'name' => 'Huyện Krông Pa', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '638', 'name' => 'Huyện Phú Thiện', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '639', 'name' => 'Huyện Chư Pưh', 'type' => 'Huyện', 'code_city' => '64'],
            ['code' => '643', 'name' => 'Thành phố Buôn Ma Thuột', 'type' => 'Thành phố', 'code_city' => '66'],
            ['code' => '644', 'name' => 'Thị xã  Buôn Hồ', 'type' => 'Thị xã', 'code_city' => '66'],
            ['code' => '645', 'name' => 'Huyện Ea H\'leo', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '646', 'name' => 'Huyện Ea Súp', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '647', 'name' => 'Huyện Buôn Đôn', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '648', 'name' => 'Huyện Cư M\'gar', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '649', 'name' => 'Huyện Krông Búk', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '650', 'name' => 'Huyện Krông Năng', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '651', 'name' => 'Huyện Ea Kar', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '652', 'name' => 'Huyện M\'Đrắk', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '653', 'name' => 'Huyện Krông Bông', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '654', 'name' => 'Huyện Krông Pắc', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '655', 'name' => 'Huyện Krông A Na', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '656', 'name' => 'Huyện Lắk', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '657', 'name' => 'Huyện Cư Kuin', 'type' => 'Huyện', 'code_city' => '66'],
            ['code' => '660', 'name' => 'Thị xã  Gia Nghĩa', 'type' => 'Thị xã', 'code_city' => '67'],
            ['code' => '661', 'name' => 'Huyện Đăk Glong', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '662', 'name' => 'Huyện Cư Jút', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '663', 'name' => 'Huyện Đắk Mil', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '664', 'name' => 'Huyện Krông Nô', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '665', 'name' => 'Huyện Đắk Song', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '666', 'name' => 'Huyện Đắk R\'Lấp', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '667', 'name' => 'Huyện Tuy Đức', 'type' => 'Huyện', 'code_city' => '67'],
            ['code' => '672', 'name' => 'Thành phố Đà Lạt', 'type' => 'Thành phố', 'code_city' => '68'],
            ['code' => '673', 'name' => 'Thành phố Bảo Lộc', 'type' => 'Thành phố', 'code_city' => '68'],
            ['code' => '674', 'name' => 'Huyện Đam Rông', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '675', 'name' => 'Huyện Lạc Dương', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '676', 'name' => 'Huyện Lâm Hà', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '677', 'name' => 'Huyện Đơn Dương', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '678', 'name' => 'Huyện Đức Trọng', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '679', 'name' => 'Huyện Di Linh', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '680', 'name' => 'Huyện Bảo Lâm', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '681', 'name' => 'Huyện Đạ Huoai', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '682', 'name' => 'Huyện Đạ Tẻh', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '683', 'name' => 'Huyện Cát Tiên', 'type' => 'Huyện', 'code_city' => '68'],
            ['code' => '688', 'name' => 'Thị xã  Phước Long', 'type' => 'Thị xã', 'code_city' => '70'],
            ['code' => '689', 'name' => 'Thị xã  Đồng Xoài', 'type' => 'Thị xã', 'code_city' => '70'],
            ['code' => '690', 'name' => 'Thị xã  Bình Long', 'type' => 'Thị xã', 'code_city' => '70'],
            ['code' => '691', 'name' => 'Huyện Bù Gia Mập', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '692', 'name' => 'Huyện Lộc Ninh', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '693', 'name' => 'Huyện Bù Đốp', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '694', 'name' => 'Huyện Hớn Quản', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '695', 'name' => 'Huyện Đồng Phú', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '696', 'name' => 'Huyện Bù Đăng', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '697', 'name' => 'Huyện Chơn Thành', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '698', 'name' => 'Huyện Phú Riềng', 'type' => 'Huyện', 'code_city' => '70'],
            ['code' => '703', 'name' => 'Thành phố Tây Ninh', 'type' => 'Thành phố', 'code_city' => '72'],
            ['code' => '705', 'name' => 'Huyện Tân Biên', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '706', 'name' => 'Huyện Tân Châu', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '707', 'name' => 'Huyện Dương Minh Châu', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '708', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '709', 'name' => 'Huyện Hòa Thành', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '710', 'name' => 'Huyện Gò Dầu', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '711', 'name' => 'Huyện Bến Cầu', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '712', 'name' => 'Huyện Trảng Bàng', 'type' => 'Huyện', 'code_city' => '72'],
            ['code' => '718', 'name' => 'Thành phố Thủ Dầu Một', 'type' => 'Thành phố', 'code_city' => '74'],
            ['code' => '719', 'name' => 'Huyện Bàu Bàng', 'type' => 'Huyện', 'code_city' => '74'],
            ['code' => '720', 'name' => 'Huyện Dầu Tiếng', 'type' => 'Huyện', 'code_city' => '74'],
            ['code' => '721', 'name' => 'Thị xã  Bến Cát', 'type' => 'Thị xã', 'code_city' => '74'],
            ['code' => '722', 'name' => 'Huyện Phú Giáo', 'type' => 'Huyện', 'code_city' => '74'],
            ['code' => '723', 'name' => 'Thị xã  Tân Uyên', 'type' => 'Thị xã', 'code_city' => '74'],
            ['code' => '724', 'name' => 'Thị xã  Dĩ An', 'type' => 'Thị xã', 'code_city' => '74'],
            ['code' => '725', 'name' => 'Thị xã  Thuận An', 'type' => 'Thị xã', 'code_city' => '74'],
            ['code' => '726', 'name' => 'Huyện Bắc Tân Uyên', 'type' => 'Huyện', 'code_city' => '74'],
            ['code' => '731', 'name' => 'Thành phố Biên Hòa', 'type' => 'Thành phố', 'code_city' => '75'],
            ['code' => '732', 'name' => 'Thị xã  Long Khánh', 'type' => 'Thị xã', 'code_city' => '75'],
            ['code' => '734', 'name' => 'Huyện Tân Phú', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '735', 'name' => 'Huyện Vĩnh Cửu', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '736', 'name' => 'Huyện Định Quán', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '737', 'name' => 'Huyện Trảng Bom', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '738', 'name' => 'Huyện Thống Nhất', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '739', 'name' => 'Huyện Cẩm Mỹ', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '740', 'name' => 'Huyện Long Thành', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '741', 'name' => 'Huyện Xuân Lộc', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '742', 'name' => 'Huyện Nhơn Trạch', 'type' => 'Huyện', 'code_city' => '75'],
            ['code' => '747', 'name' => 'Thành phố Vũng Tàu', 'type' => 'Thành phố', 'code_city' => '77'],
            ['code' => '748', 'name' => 'Thành phố Bà Rịa', 'type' => 'Thành phố', 'code_city' => '77'],
            ['code' => '750', 'name' => 'Huyện Châu Đức', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '751', 'name' => 'Huyện Xuyên Mộc', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '752', 'name' => 'Huyện Long Điền', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '753', 'name' => 'Huyện Đất Đỏ', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '754', 'name' => 'Huyện Tân Thành', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '755', 'name' => 'Huyện Côn Đảo', 'type' => 'Huyện', 'code_city' => '77'],
            ['code' => '760', 'name' => 'Quận 1', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '761', 'name' => 'Quận 12', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '762', 'name' => 'Quận Thủ Đức', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '763', 'name' => 'Quận 9', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '764', 'name' => 'Quận Gò Vấp', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '765', 'name' => 'Quận Bình Thạnh', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '766', 'name' => 'Quận Tân Bình', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '767', 'name' => 'Quận Tân Phú', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '768', 'name' => 'Quận Phú Nhuận', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '769', 'name' => 'Quận 2', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '770', 'name' => 'Quận 3', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '771', 'name' => 'Quận 10', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '772', 'name' => 'Quận 11', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '773', 'name' => 'Quận 4', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '774', 'name' => 'Quận 5', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '775', 'name' => 'Quận 6', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '776', 'name' => 'Quận 8', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '777', 'name' => 'Quận Bình Tân', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '778', 'name' => 'Quận 7', 'type' => 'Quận', 'code_city' => '79'],
            ['code' => '783', 'name' => 'Huyện Củ Chi', 'type' => 'Huyện', 'code_city' => '79'],
            ['code' => '784', 'name' => 'Huyện Hóc Môn', 'type' => 'Huyện', 'code_city' => '79'],
            ['code' => '785', 'name' => 'Huyện Bình Chánh', 'type' => 'Huyện', 'code_city' => '79'],
            ['code' => '786', 'name' => 'Huyện Nhà Bè', 'type' => 'Huyện', 'code_city' => '79'],
            ['code' => '787', 'name' => 'Huyện Cần Giờ', 'type' => 'Huyện', 'code_city' => '79'],
            ['code' => '794', 'name' => 'Thành phố Tân An', 'type' => 'Thành phố', 'code_city' => '80'],
            ['code' => '795', 'name' => 'Thị xã  Kiến Tường', 'type' => 'Thị xã', 'code_city' => '80'],
            ['code' => '796', 'name' => 'Huyện Tân Hưng', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '797', 'name' => 'Huyện Vĩnh Hưng', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '798', 'name' => 'Huyện Mộc Hóa', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '799', 'name' => 'Huyện Tân Thạnh', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '800', 'name' => 'Huyện Thạnh Hóa', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '801', 'name' => 'Huyện Đức Huệ', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '802', 'name' => 'Huyện Đức Hòa', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '803', 'name' => 'Huyện Bến Lức', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '804', 'name' => 'Huyện Thủ Thừa', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '805', 'name' => 'Huyện Tân Trụ', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '806', 'name' => 'Huyện Cần Đước', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '807', 'name' => 'Huyện Cần Giuộc', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '808', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '80'],
            ['code' => '815', 'name' => 'Thành phố Mỹ Tho', 'type' => 'Thành phố', 'code_city' => '82'],
            ['code' => '816', 'name' => 'Thị xã  Gò Công', 'type' => 'Thị xã', 'code_city' => '82'],
            ['code' => '817', 'name' => 'Thị xã  Cai Lậy', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '818', 'name' => 'Huyện Tân Phước', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '819', 'name' => 'Huyện Cái Bè', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '820', 'name' => 'Huyện Cai Lậy', 'type' => 'Thị xã', 'code_city' => '82'],
            ['code' => '821', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '822', 'name' => 'Huyện Chợ Gạo', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '823', 'name' => 'Huyện Gò Công Tây', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '824', 'name' => 'Huyện Gò Công Đông', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '825', 'name' => 'Huyện Tân Phú Đông', 'type' => 'Huyện', 'code_city' => '82'],
            ['code' => '829', 'name' => 'Thành phố Bến Tre', 'type' => 'Thành phố', 'code_city' => '83'],
            ['code' => '831', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '832', 'name' => 'Huyện Chợ Lách', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '833', 'name' => 'Huyện Mỏ Cày Nam', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '834', 'name' => 'Huyện Giồng Trôm', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '835', 'name' => 'Huyện Bình Đại', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '836', 'name' => 'Huyện Ba Tri', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '837', 'name' => 'Huyện Thạnh Phú', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '838', 'name' => 'Huyện Mỏ Cày Bắc', 'type' => 'Huyện', 'code_city' => '83'],
            ['code' => '842', 'name' => 'Thành phố Trà Vinh', 'type' => 'Thành phố', 'code_city' => '84'],
            ['code' => '844', 'name' => 'Huyện Càng Long', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '845', 'name' => 'Huyện Cầu Kè', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '846', 'name' => 'Huyện Tiểu Cần', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '847', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '848', 'name' => 'Huyện Cầu Ngang', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '849', 'name' => 'Huyện Trà Cú', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '850', 'name' => 'Huyện Duyên Hải', 'type' => 'Huyện', 'code_city' => '84'],
            ['code' => '851', 'name' => 'Thị xã  Duyên Hải', 'type' => 'Thị xã', 'code_city' => '84'],
            ['code' => '855', 'name' => 'Thành phố Vĩnh Long', 'type' => 'Thành phố', 'code_city' => '86'],
            ['code' => '857', 'name' => 'Huyện Long Hồ', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '858', 'name' => 'Huyện Mang Thít', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '859', 'name' => 'Huyện  Vũng Liêm', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '860', 'name' => 'Huyện Tam Bình', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '861', 'name' => 'Thị xã  Bình Minh', 'type' => 'Thị xã', 'code_city' => '86'],
            ['code' => '862', 'name' => 'Huyện Trà Ôn', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '863', 'name' => 'Huyện Bình Tân', 'type' => 'Huyện', 'code_city' => '86'],
            ['code' => '866', 'name' => 'Thành phố Cao Lãnh', 'type' => 'Thành phố', 'code_city' => '87'],
            ['code' => '867', 'name' => 'Thành phố Sa Đéc', 'type' => 'Thành phố', 'code_city' => '87'],
            ['code' => '868', 'name' => 'Thị xã  Hồng Ngự', 'type' => 'Thị xã', 'code_city' => '87'],
            ['code' => '869', 'name' => 'Huyện Tân Hồng', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '870', 'name' => 'Huyện Hồng Ngự', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '871', 'name' => 'Huyện Tam Nông', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '872', 'name' => 'Huyện Tháp Mười', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '873', 'name' => 'Huyện Cao Lãnh', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '874', 'name' => 'Huyện Thanh Bình', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '875', 'name' => 'Huyện Lấp Vò', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '876', 'name' => 'Huyện Lai Vung', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '877', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '87'],
            ['code' => '883', 'name' => 'Thành phố Long Xuyên', 'type' => 'Thành phố', 'code_city' => '89'],
            ['code' => '884', 'name' => 'Thành phố Châu Đốc', 'type' => 'Thành phố', 'code_city' => '89'],
            ['code' => '886', 'name' => 'Huyện An Phú', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '887', 'name' => 'Thị xã  Tân Châu', 'type' => 'Thị xã', 'code_city' => '89'],
            ['code' => '888', 'name' => 'Huyện Phú Tân', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '889', 'name' => 'Huyện Châu Phú', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '890', 'name' => 'Huyện Tịnh Biên', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '891', 'name' => 'Huyện Tri Tôn', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '892', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '893', 'name' => 'Huyện Chợ Mới', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '894', 'name' => 'Huyện Thoại Sơn', 'type' => 'Huyện', 'code_city' => '89'],
            ['code' => '899', 'name' => 'Thành phố Rạch Giá', 'type' => 'Thành phố', 'code_city' => '91'],
            ['code' => '900', 'name' => 'Thị xã  Hà Tiên', 'type' => 'Thị xã', 'code_city' => '91'],
            ['code' => '902', 'name' => 'Huyện Kiên Lương', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '903', 'name' => 'Huyện Hòn Đất', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '904', 'name' => 'Huyện Tân Hiệp', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '905', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '906', 'name' => 'Huyện Giồng Riềng', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '907', 'name' => 'Huyện Gò Quao', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '908', 'name' => 'Huyện An Biên', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '909', 'name' => 'Huyện An Minh', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '910', 'name' => 'Huyện Vĩnh Thuận', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '911', 'name' => 'Huyện Phú Quốc', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '912', 'name' => 'Huyện Kiên Hải', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '913', 'name' => 'Huyện U Minh Thượng', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '914', 'name' => 'Huyện Giang Thành', 'type' => 'Huyện', 'code_city' => '91'],
            ['code' => '916', 'name' => 'Quận Ninh Kiều', 'type' => 'Quận', 'code_city' => '92'],
            ['code' => '917', 'name' => 'Quận Ô Môn', 'type' => 'Quận', 'code_city' => '92'],
            ['code' => '918', 'name' => 'Quận Bình Thuỷ', 'type' => 'Quận', 'code_city' => '92'],
            ['code' => '919', 'name' => 'Quận Cái Răng', 'type' => 'Quận', 'code_city' => '92'],
            ['code' => '923', 'name' => 'Quận Thốt Nốt', 'type' => 'Quận', 'code_city' => '92'],
            ['code' => '924', 'name' => 'Huyện Vĩnh Thạnh', 'type' => 'Huyện', 'code_city' => '92'],
            ['code' => '925', 'name' => 'Huyện Cờ Đỏ', 'type' => 'Huyện', 'code_city' => '92'],
            ['code' => '926', 'name' => 'Huyện Phong Điền', 'type' => 'Huyện', 'code_city' => '92'],
            ['code' => '927', 'name' => 'Huyện Thới Lai', 'type' => 'Huyện', 'code_city' => '92'],
            ['code' => '930', 'name' => 'Thành phố Vị Thanh', 'type' => 'Thành phố', 'code_city' => '93'],
            ['code' => '931', 'name' => 'Thị xã  Ngã Bảy', 'type' => 'Thị xã', 'code_city' => '93'],
            ['code' => '932', 'name' => 'Huyện Châu Thành A', 'type' => 'Huyện', 'code_city' => '93'],
            ['code' => '933', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '93'],
            ['code' => '934', 'name' => 'Huyện Phụng Hiệp', 'type' => 'Huyện', 'code_city' => '93'],
            ['code' => '935', 'name' => 'Huyện Vị Thuỷ', 'type' => 'Huyện', 'code_city' => '93'],
            ['code' => '936', 'name' => 'Huyện Long Mỹ', 'type' => 'Huyện', 'code_city' => '93'],
            ['code' => '937', 'name' => 'Thị xã  Long Mỹ', 'type' => 'Thị xã', 'code_city' => '93'],
            ['code' => '941', 'name' => 'Thành phố Sóc Trăng', 'type' => 'Thành phố', 'code_city' => '94'],
            ['code' => '942', 'name' => 'Huyện Châu Thành', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '943', 'name' => 'Huyện Kế Sách', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '944', 'name' => 'Huyện Mỹ Tú', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '945', 'name' => 'Huyện Cù Lao Dung', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '946', 'name' => 'Huyện Long Phú', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '947', 'name' => 'Huyện Mỹ Xuyên', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '948', 'name' => 'Thị xã  Ngã Năm', 'type' => 'Thị xã', 'code_city' => '94'],
            ['code' => '949', 'name' => 'Huyện Thạnh Trị', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '950', 'name' => 'Thị xã  Vĩnh Châu', 'type' => 'Thị xã', 'code_city' => '94'],
            ['code' => '951', 'name' => 'Huyện Trần Đề', 'type' => 'Huyện', 'code_city' => '94'],
            ['code' => '954', 'name' => 'Thành phố Bạc Liêu', 'type' => 'Thành phố', 'code_city' => '95'],
            ['code' => '956', 'name' => 'Huyện Hồng Dân', 'type' => 'Huyện', 'code_city' => '95'],
            ['code' => '957', 'name' => 'Huyện Phước Long', 'type' => 'Huyện', 'code_city' => '95'],
            ['code' => '958', 'name' => 'Huyện Vĩnh Lợi', 'type' => 'Huyện', 'code_city' => '95'],
            ['code' => '959', 'name' => 'Thị xã  Giá Rai', 'type' => 'Thị xã', 'code_city' => '95'],
            ['code' => '960', 'name' => 'Huyện Đông Hải', 'type' => 'Huyện', 'code_city' => '95'],
            ['code' => '961', 'name' => 'Huyện Hoà Bình', 'type' => 'Huyện', 'code_city' => '95'],
            ['code' => '964', 'name' => 'Thành phố Cà Mau', 'type' => 'Thành phố', 'code_city' => '96'],
            ['code' => '966', 'name' => 'Huyện U Minh', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '967', 'name' => 'Huyện Thới Bình', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '968', 'name' => 'Huyện Trần Văn Thời', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '969', 'name' => 'Huyện Cái Nước', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '970', 'name' => 'Huyện Đầm Dơi', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '971', 'name' => 'Huyện Năm Căn', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '972', 'name' => 'Huyện Phú Tân', 'type' => 'Huyện', 'code_city' => '96'],
            ['code' => '973', 'name' => 'Huyện Ngọc Hiển', 'type' => 'Huyện', 'code_city' => '96']
        ];

        DB::table('districts')->insert($districts);

        // $this->call(UsersTableSeeder::class);
    }
}
